# Final Assessments

## Isiah Lloyd

My individual contribution towards our senior design project was development of the web extension, or the part of the application that the user interacts with. Web extensions are built using web technologies like HTML, CSS, and Javascript. I already had experience in these technologies as well as developing web extensions coming into the project so it makes sense for me to take on this part of the project. This allowed me to complete the extension to our planned specification fairly fast, which allowed me to work on “bonus” features that went beyond our original scope, improved our product, and let me learn new things. 

The new main features I was able to add was a keyboard shortcut to activate the extension and a settings page. I had never used the web extension “command” API, which allows you to register a keyboard shortcut with the browser and any use of that shortcut will send an event to your code. I ran into two problems when developing this, one was that I wanted the user to be able to change the keyboard shortcut from within the settings page I built, but that was not allowed as it would be a security concern so the best I could do would directly link to the browser’s keyboard shortcut page. Another problem I ran into was when I was testing the extension on Microsoft Edge. I set the default shortcut combination to be Ctrl+Shift+S (as it was easy to use with one hand and S could stand for speak!). This worked fine on Chrome which I did the majority of my testing but in Edge, it did not work in Edge as there was already a built in tool associated with that shortcut, so I had to change the shortcut. 

I was proud of the settings page I made; it allowed the user to change some setting related to the text to speech engine. A user can change the voice the engine uses, the rate the engine speaks at, and the pitch of the voice all on this page. Now this wasn’t that hard to put together, but what was more interesting to implement was using the storage.sync API, which stores the user’s settings in the cloud. For example, if they login to Chrome on another device, the extension and the settings the user set will automatically be downloaded. 
